/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pasien;
import dokter.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import koneksi.koneksi;
/**
 *
 * @author jeremiamanogi
 */
public class Pasien extends javax.swing.JFrame implements ActionListener {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    List<String> jenisLayanan;
protected void datatable(){
        Object[] Baris = {
            "ID", 
            "Nama Panjang", 
            "Jenis Kelamin", 
            "No. Telepon", 
            "Tanggal Lahir", 
            "Status"
        };

        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "SELECT id, nama_panjang, jenis_kelamin, nomor_telepon, tanggal_lahir, status_aktif " +
                         "FROM pasien " +
                         "WHERE nama_panjang LIKE '%" + cariitem + "%' " +
                         "OR nomor_identitas LIKE '%" + cariitem + "%' " +
                         "ORDER BY id ASC";

            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
    //            String status = hasil.getInt("status_aktif") == 1 ? "Aktif" : "Tidak Aktif";

                tabmode.addRow(new Object[]{
                    hasil.getInt("id"),
                    hasil.getString("nama_panjang"),
                    hasil.getString("jenis_kelamin"),
                    hasil.getString("nomor_telepon"),
                    hasil.getDate("tanggal_lahir"),
                    hasil.getInt("status_aktif")
                });
            }

            tblplgn.setModel(tabmode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
        }
    }
    protected void aktif(){
        txtid.requestFocus();
    }
    
    protected void kosong(){
        txtid.setText("");
        txtnm.setText("");
        txtidentity.setText("");
        txtRm.setText("");
        txtNip.setText("");
        txtPob.setText("");
        txtDob.setText("");
        txtcari.setText("");
        txtAddresh.setText("");
        txtPhone.setText("");
        buttonGroupRadio.clearSelection();
        chkActive.setEnabled(false);
        chkActive.setSelected(true);
    }    
    /**
     * Creates new form Pelanggan
     */
    public Pasien() {
        initComponents();
//        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent e) {
//                if (parent != null) {
//                    parent.setEnabled(true);
//                    parent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                    parent.datatable();
//                    parent.kosong();
//                    setVisible(false);
//                }
//                
//                if (docterParent != null) {
//                    docterParent.setEnabled(true);
//                    docterParent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                    docterParent.datatable();
//                    docterParent.kosong();
//                    setVisible(false);
//                }
//            }
//        });

        String[] golonganDarah = {
            "A+","A-","B+","B-","AB+","AB-","O+","O-","Tidak_Tahu"
        };
        cmbGolonganDarah.setModel(new DefaultComboBoxModel<>(golonganDarah));
        String[] indetity = {
            "KTP","SIM","Paspor","Kartu_Pelajar","Kitas","Lainnya"
        };
        cmbIndentity.setModel(new DefaultComboBoxModel<>(indetity));

        aktif();
        kosong();
        datatable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadio = new javax.swing.ButtonGroup();
        bsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtidentity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        cmbGolonganDarah = new javax.swing.JComboBox<>();
        txtRm = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddresh = new javax.swing.JTextArea();
        txtnm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        txtPob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rLaki = new javax.swing.JRadioButton();
        rPrempuan = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        cmbIndentity = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(this::bsimpanActionPerformed);
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 293, -1, -1));

        jLabel1.setText("Data Pasien");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, -1));

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblplgnMouseMoved(evt);
            }
        });
        tblplgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblplgn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 351, 869, 275));

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 322, 140, -1));

        bcari.setText("Cari");
        bcari.addActionListener(this::bcariActionPerformed);
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 322, -1, -1));

        bubah.setText("Ubah");
        bubah.addActionListener(this::bubahActionPerformed);
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 293, -1, -1));

        bhapus.setText("Hapus");
        bhapus.addActionListener(this::bhapusActionPerformed);
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 293, -1, -1));

        bbatal.setText("Batal");
        bbatal.addActionListener(this::bbatalActionPerformed);
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 293, -1, -1));

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(this::bkeluarActionPerformed);
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 293, -1, -1));

        jLabel2.setText("ID Pasien");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 32, -1, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 29, 246, -1));

        jLabel3.setText("Nama Panjang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 58, -1, -1));
        getContentPane().add(txtidentity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 246, -1));

        jLabel4.setText("Nomor Identitas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 87, -1, -1));

        jLabel5.setText("Nomor Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jLabel6.setText("Nomor Rekam Medis");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        chkActive.setSelected(true);
        chkActive.setText("Status Aktif");
        chkActive.setEnabled(false);
        chkActive.setIconTextGap(8);
        chkActive.addActionListener(this::chkActiveActionPerformed);
        getContentPane().add(chkActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        getContentPane().add(cmbGolonganDarah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 246, -1));

        txtRm.addActionListener(this::txtRmActionPerformed);
        getContentPane().add(txtRm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 246, -1));

        txtAddresh.setColumns(20);
        txtAddresh.setRows(5);
        jScrollPane2.setViewportView(txtAddresh);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 246, -1));
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 58, 246, -1));

        jLabel7.setText("Nomor Induk Pegawai");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtNip.addActionListener(this::txtNipActionPerformed);
        getContentPane().add(txtNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 246, -1));

        txtPob.addActionListener(this::txtPobActionPerformed);
        getContentPane().add(txtPob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 246, -1));

        jLabel8.setText("Tempat Lahir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        txtPhone.addActionListener(this::txtPhoneActionPerformed);
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 246, -1));

        jLabel10.setText("Tanggal Lahir");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        buttonGroupRadio.add(rLaki);
        rLaki.setText("Laki-Laki");
        rLaki.addActionListener(this::rLakiActionPerformed);
        getContentPane().add(rLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        buttonGroupRadio.add(rPrempuan);
        rPrempuan.setText("Perempuan");
        rPrempuan.addActionListener(this::rPrempuanActionPerformed);
        getContentPane().add(rPrempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jLabel11.setText("Jenis Nomor Identitas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 121, -1, -1));

        getContentPane().add(cmbIndentity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 246, -1));

        jLabel12.setText("Golongan Darah");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel13.setText("Alamat");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        txtDob.addActionListener(this::txtDobActionPerformed);
        getContentPane().add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 246, -1));
    }// </editor-fold>//GEN-END:initComponents

    /*
    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
     String sql = "INSERT INTO pasien (" +
                 "nama_panjang, nomor_identitas, jenis_nomor_identitas, " +
                 "nomor_rekam_medis, nomor_induk_pegawai, tempat_lahir, tanggal_lahir, " +
                 "jenis_kelamin, golongan_darah, alamat_lengkap, nomor_telepon, " +
                 "id_perusahaan, nip_karyawan, status_aktif) " +
                 "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

    try {
        
        txtnm.setText("");
        txtidentity.setText("");
        txtRm.setText("");
        txtNip.setText("");
        txtPob.setText("");
        txtDob.setText("");
        txtcari.setText("");
        txtAddresh.setText("");
        txtPhone.setText("");
        buttonGroupRadio.clearSelection();
        chkActive.setEnabled(false);
        chkActive.setSelected(true);

        PreparedStatement stat = conn.prepareStatement(sql);

        stat.setString(1, txtnm.getText());
        stat.setString(2, txtNomorIdentitas.getText());
        stat.setString(3, txtJenisIdentitas.getText()); // contoh: KTP
        stat.setString(4, txtNoRM.getText());
        stat.setString(5, txtNIP.getText());
        stat.setString(6, txtTempatLahir.getText());

        // format tanggal harus yyyy-MM-dd
        stat.setDate(7, java.sql.Date.valueOf(txtTanggalLahir.getText()));

        stat.setString(8, txtJenisKelamin.getText()); // Laki-laki / Perempuan
        stat.setString(9, txtGolonganDarah.getText()); // A+, O-, dll
        stat.setString(10, txtAlamat.getText());
        stat.setString(11, txtTelepon.getText());

        // id_perusahaan boleh null
        if (txtPerusahaan.getText().isEmpty()) {
            stat.setNull(12, java.sql.Types.INTEGER);
        } else {
            stat.setInt(13, null);
        }

        stat.setString(14, txtNipKaryawan.getText());

        int status = chkActive.isSelected() ? 1 : 0;
        stat.setInt(15, status);

        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        kosong();
        txtId.requestFocus();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
    }

    }//GEN-LAST:event_bsimpanActionPerformed
*/
    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {                                        
    String sql = "INSERT INTO pasien (" +
                 "nama_panjang, nomor_identitas, jenis_nomor_identitas, " +
                 "nomor_rekam_medis, nomor_induk_pegawai, tempat_lahir, tanggal_lahir, " +
                 "jenis_kelamin, golongan_darah, alamat_lengkap, nomor_telepon, status_aktif) " +
                 "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

    try {
        PreparedStatement stat = conn.prepareStatement(sql);

        stat.setString(1, txtnm.getText());
        stat.setString(2, txtidentity.getText());
        stat.setString(3, cmbIndentity.getSelectedItem().toString());
        stat.setString(4, txtRm.getText());
        stat.setString(5, txtNip.getText());
        stat.setString(6, txtPob.getText());

        // format: yyyy-MM-dd
        stat.setDate(7, java.sql.Date.valueOf(txtDob.getText()));
       String jenis = null;
        if(rLaki.isSelected()){
            jenis = "Laki-Laki";
        }else if(rPrempuan.isSelected()){
            jenis = "Perempuan";
        }

        stat.setString(8, jenis);
        stat.setString(9, cmbGolonganDarah.getSelectedItem().toString());
        stat.setString(10, txtAddresh.getText());
        stat.setString(11, txtPhone.getText());

        int status = chkActive.isSelected() ? 1 : 0;
        stat.setInt(12, status);

        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        kosong();
        txtnm.requestFocus();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
    }

    datatable();
    }
    /*
private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {                                        

}
    */
    private void tblplgnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseMoved

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
    String sql = "UPDATE pasien SET " +
                 "nama_panjang=?, nomor_identitas=?, jenis_nomor_identitas=?, " +
                 "nomor_rekam_medis=?, nomor_induk_pegawai=?, tempat_lahir=?, tanggal_lahir=?, " +
                 "jenis_kelamin=?, golongan_darah=?, alamat_lengkap=?, nomor_telepon=?, status_aktif=? " +
                 "WHERE id=?";

    try {
        PreparedStatement stat = conn.prepareStatement(sql);

        stat.setString(1, txtnm.getText());
        stat.setString(2, txtidentity.getText());
        stat.setString(3, cmbIndentity.getSelectedItem().toString());
        stat.setString(4, txtRm.getText());
        stat.setString(5, txtNip.getText());
        stat.setString(6, txtPob.getText());

        // format: yyyy-MM-dd
        stat.setDate(7, java.sql.Date.valueOf(txtDob.getText()));

        String jenis = null;
        if (rLaki.isSelected()) {
            jenis = "Laki-laki"; // ⚠️ harus sama dengan enum DB
        } else if (rPrempuan.isSelected()) {
            jenis = "Perempuan";
        }

        stat.setString(8, jenis);
        stat.setString(9, cmbGolonganDarah.getSelectedItem().toString());
        stat.setString(10, txtAddresh.getText());
        stat.setString(11, txtPhone.getText());

        int status = chkActive.isSelected() ? 1 : 0;
        stat.setInt(12, status);

        // WHERE id = ?
        stat.setInt(13, Integer.parseInt(txtid.getText()));

        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
        kosong();
        txtnm.requestFocus();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal diupdate: " + e.getMessage());
    }

    datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from pasien where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        int bar = tblplgn.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        try {
            String sql = "SELECT * FROM pasien where id = " + a;

            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
               txtid.setText(hasil.getString(1));
               txtnm.setText(hasil.getString(2));
               txtidentity.setText(hasil.getString(3));
               txtRm.setText(hasil.getString(5));
               txtNip.setText(hasil.getString(6));
               txtPob.setText(hasil.getString(7));
               txtDob.setText(hasil.getString(8));
               txtAddresh.setText(hasil.getString(11));
               txtPhone.setText(hasil.getString(12));
            if ("Laki-Laki".equals(hasil.getString(9))) {
                rLaki.setSelected(true);
            } else {
                rPrempuan.setSelected(true);
            }
            String aktif = hasil.getString(15);
               chkActive.setEnabled(true);
               chkActive.setSelected(aktif.equals("1"));
            }

            tblplgn.setModel(tabmode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
        }
    }//GEN-LAST:event_tblplgnMouseClicked
    /*
        Object[] Baris = {
            "ID", 
            "Nama Panjang", 
            "Jenis Kelamin", 
            "No. Telepon", 
            "Tanggal Lahir", 
            "Status"
        };

        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "SELECT id, nama_panjang, jenis_kelamin, nomor_telepon, tanggal_lahir, status_aktif " +
                         "FROM pasien " +
                         "WHERE nama_panjang LIKE '%" + cariitem + "%' " +
                         "OR nomor_identitas LIKE '%" + cariitem + "%' " +
                         "ORDER BY id ASC";

            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
    //            String status = hasil.getInt("status_aktif") == 1 ? "Aktif" : "Tidak Aktif";

                tabmode.addRow(new Object[]{
                    hasil.getInt("id"),
                    hasil.getString("nama_panjang"),
                    hasil.getString("jenis_kelamin"),
                    hasil.getString("nomor_telepon"),
                    hasil.getDate("tanggal_lahir"),
                    hasil.getInt("status_aktif")
                });
            }

            tblplgn.setModel(tabmode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
        }
    */
    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void chkActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkActiveActionPerformed

    private void txtRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRmActionPerformed

    private void txtNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNipActionPerformed

    private void txtPobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPobActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void rLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLakiActionPerformed

    private void rPrempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPrempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPrempuanActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroupRadio;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JComboBox<String> cmbGolonganDarah;
    private javax.swing.JComboBox<String> cmbIndentity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rLaki;
    private javax.swing.JRadioButton rPrempuan;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextArea txtAddresh;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPob;
    private javax.swing.JTextField txtRm;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidentity;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
