/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasien;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Acer
 */
public class Pasien extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    List<String> jenisLayanan;
protected void datatable(){
        Object[] Baris = {
            "ID", 
            "Nama Panjang", 
            "Jenis Kelamin", 
            "No. Telepon", 
            "Tanggal Lahir", 
            "Status"
        };

        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "SELECT id, nama_panjang, jenis_kelamin, nomor_telepon, tanggal_lahir, status_aktif " +
                         "FROM pasien " +
                         "WHERE nama_panjang LIKE '%" + cariitem + "%' " +
                         "OR nomor_identitas LIKE '%" + cariitem + "%' " +
                         "ORDER BY id ASC";

            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
    //            String status = hasil.getInt("status_aktif") == 1 ? "Aktif" : "Tidak Aktif";

                tabmode.addRow(new Object[]{
                    hasil.getInt("id"),
                    hasil.getString("nama_panjang"),
                    hasil.getString("jenis_kelamin"),
                    hasil.getString("nomor_telepon"),
                    hasil.getDate("tanggal_lahir"),
                    hasil.getInt("status_aktif")
                });
            }

            tblplgn.setModel(tabmode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
        }
    }
    protected void aktif(){
        txtid.requestFocus();
    }
    
    protected void kosong(){
        txtid.setText("");
        txtnm.setText("");
        txtidentity.setText("");
        txtRm.setText("");
        txtNip.setText("");
        txtPob.setText("");
        txtDob.setText("");
        txtcari.setText("");
        txtAddresh.setText("");
        txtPhone.setText("");
        buttonGroup1.clearSelection();
        chkActive.setEnabled(false);
        chkActive.setSelected(true);
    }    
    /**
     * Creates new form Pelanggan
     */
    public Pasien() {
        initComponents();
//        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent e) {
//                if (parent != null) {
//                    parent.setEnabled(true);
//                    parent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                    parent.datatable();
//                    parent.kosong();
//                    setVisible(false);
//                }
//                
//                if (docterParent != null) {
//                    docterParent.setEnabled(true);
//                    docterParent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                    docterParent.datatable();
//                    docterParent.kosong();
//                    setVisible(false);
//                }
//            }
//        });

        String[] golonganDarah = {
            "A+","A-","B+","B-","AB+","AB-","O+","O-","Tidak_Tahu"
        };
        cmbGolonganDarah.setModel(new DefaultComboBoxModel<>(golonganDarah));
        String[] indetity = {
            "KTP","SIM","Paspor","Kartu_Pelajar","Kitas","Lainnya"
        };
        cmbIndentity.setModel(new DefaultComboBoxModel<>(indetity));

        aktif();
        kosong();
        datatable();
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtidentity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        cmbGolonganDarah = new javax.swing.JComboBox<>();
        txtRm = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddresh = new javax.swing.JTextArea();
        txtnm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        txtPob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rLaki = new javax.swing.JRadioButton();
        rPrempuan = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        cmbIndentity = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Pasien");

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblplgnMouseMoved(evt);
            }
        });
        tblplgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblplgn);

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Pasien");

        txtid.setEnabled(false);

        jLabel3.setText("Nama Panjang");

        jLabel4.setText("Nomor Identitas");

        jLabel5.setText("Nomor Telepon");

        jLabel6.setText("Nomor Rekam Medis");

        chkActive.setSelected(true);
        chkActive.setText("Status Aktif");
        chkActive.setEnabled(false);
        chkActive.setIconTextGap(8);
        chkActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActiveActionPerformed(evt);
            }
        });

        txtRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRmActionPerformed(evt);
            }
        });

        txtAddresh.setColumns(20);
        txtAddresh.setRows(5);
        jScrollPane2.setViewportView(txtAddresh);

        jLabel7.setText("Nomor Induk Pegawai");

        txtNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNipActionPerformed(evt);
            }
        });

        txtPob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPobActionPerformed(evt);
            }
        });

        jLabel8.setText("Tempat Lahir");

        jLabel9.setText("Jenis Kelamin");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        jLabel10.setText("Tanggal Lahir");

        buttonGroup1.add(rLaki);
        rLaki.setText("Laki-Laki");
        rLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rPrempuan);
        rPrempuan.setText("Perempuan");
        rPrempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPrempuanActionPerformed(evt);
            }
        });

        jLabel11.setText("Jenis Nomor Identitas");

        jLabel12.setText("Golongan Darah");

        jLabel13.setText("Alamat");

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(87, 87, 87)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jLabel10)
                            .addGap(62, 62, 62)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(57, 57, 57)
                            .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jLabel9)
                            .addGap(63, 63, 63)
                            .addComponent(rLaki)
                            .addGap(13, 13, 13)
                            .addComponent(rPrempuan))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(53, 53, 53)
                            .addComponent(txtidentity, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel12)
                            .addGap(49, 49, 49)
                            .addComponent(cmbGolonganDarah, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbIndentity, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRm, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPob, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel5))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(564, 564, 564)
                            .addComponent(chkActive))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bsimpan)
                            .addGap(5, 5, 5)
                            .addComponent(bubah)
                            .addGap(17, 17, 17)
                            .addComponent(bhapus)
                            .addGap(11, 11, 11)
                            .addComponent(bbatal)
                            .addGap(17, 17, 17)
                            .addComponent(bkeluar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(bcari))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel2))
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel10))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(rLaki)
                                .addComponent(rPrempuan))))
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtidentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(cmbGolonganDarah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel11)
                            .addGap(13, 13, 13)
                            .addComponent(jLabel6)
                            .addGap(14, 14, 14)
                            .addComponent(jLabel7)
                            .addGap(14, 14, 14)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cmbIndentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(txtRm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(txtPob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(84, 84, 84)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(chkActive)
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bsimpan)
                        .addComponent(bubah)
                        .addComponent(bhapus)
                        .addComponent(bbatal)
                        .addComponent(bkeluar))
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bcari))
                    .addGap(4, 4, 4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        
    String sql = "INSERT INTO pasien (" +
                 "nama_panjang, nomor_identitas, jenis_nomor_identitas, " +
                 "nomor_rekam_medis, nomor_induk_pegawai, tempat_lahir, tanggal_lahir, " +
                 "jenis_kelamin, golongan_darah, alamat_lengkap, nomor_telepon, status_aktif) " +
                 "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

    try {
        PreparedStatement stat = conn.prepareStatement(sql);

        stat.setString(1, txtnm.getText());
        stat.setString(2, txtidentity.getText());
        stat.setString(3, cmbIndentity.getSelectedItem().toString());
        stat.setString(4, txtRm.getText());
        stat.setString(5, txtNip.getText());
        stat.setString(6, txtPob.getText());

        // format: yyyy-MM-dd
        stat.setDate(7, java.sql.Date.valueOf(txtDob.getText()));
       String jenis = null;
        if(rLaki.isSelected()){
            jenis = "Laki-Laki";
        }else if(rPrempuan.isSelected()){
            jenis = "Perempuan";
        }

        stat.setString(8, jenis);
        stat.setString(9, cmbGolonganDarah.getSelectedItem().toString());
        stat.setString(10, txtAddresh.getText());
        stat.setString(11, txtPhone.getText());

        int status = chkActive.isSelected() ? 1 : 0;
        stat.setInt(12, status);

        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        kosong();
        txtnm.requestFocus();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
    }

    datatable();
        
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tblplgnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseMoved

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        int bar = tblplgn.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        try {
            String sql = "SELECT * FROM pasien where id = " + a;

            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
                txtid.setText(hasil.getString(1));
                txtnm.setText(hasil.getString(2));
                txtidentity.setText(hasil.getString(3));
                txtRm.setText(hasil.getString(5));
                txtNip.setText(hasil.getString(6));
                txtPob.setText(hasil.getString(7));
                txtDob.setText(hasil.getString(8));
                txtAddresh.setText(hasil.getString(11));
                txtPhone.setText(hasil.getString(12));
                if ("Laki-Laki".equals(hasil.getString(9))) {
                    rLaki.setSelected(true);
                } else {
                    rPrempuan.setSelected(true);
                }
                String aktif = hasil.getString(15);
                chkActive.setEnabled(true);
                chkActive.setSelected(aktif.equals("1"));
            }

            tblplgn.setModel(tabmode);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
        }
    }//GEN-LAST:event_tblplgnMouseClicked

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        String sql = "UPDATE pasien SET " +
        "nama_panjang=?, nomor_identitas=?, jenis_nomor_identitas=?, " +
        "nomor_rekam_medis=?, nomor_induk_pegawai=?, tempat_lahir=?, tanggal_lahir=?, " +
        "jenis_kelamin=?, golongan_darah=?, alamat_lengkap=?, nomor_telepon=?, status_aktif=? " +
        "WHERE id=?";

        try {
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, txtnm.getText());
            stat.setString(2, txtidentity.getText());
            stat.setString(3, cmbIndentity.getSelectedItem().toString());
            stat.setString(4, txtRm.getText());
            stat.setString(5, txtNip.getText());
            stat.setString(6, txtPob.getText());

            // format: yyyy-MM-dd
            stat.setDate(7, java.sql.Date.valueOf(txtDob.getText()));

            String jenis = null;
            if (rLaki.isSelected()) {
                jenis = "Laki-laki"; // ⚠️ harus sama dengan enum DB
            } else if (rPrempuan.isSelected()) {
                jenis = "Perempuan";
            }

            stat.setString(8, jenis);
            stat.setString(9, cmbGolonganDarah.getSelectedItem().toString());
            stat.setString(10, txtAddresh.getText());
            stat.setString(11, txtPhone.getText());

            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(12, status);

            // WHERE id = ?
            stat.setInt(13, Integer.parseInt(txtid.getText()));

            stat.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
            kosong();
            txtnm.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal diupdate: " + e.getMessage());
        }

        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from pasien where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void chkActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkActiveActionPerformed

    private void txtRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRmActionPerformed

    private void txtNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNipActionPerformed

    private void txtPobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPobActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void rLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLakiActionPerformed

    private void rPrempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPrempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPrempuanActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JComboBox<String> cmbGolonganDarah;
    private javax.swing.JComboBox<String> cmbIndentity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rLaki;
    private javax.swing.JRadioButton rPrempuan;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextArea txtAddresh;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPob;
    private javax.swing.JTextField txtRm;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidentity;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables
}
