/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dokter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import koneksi.koneksi;
/**
 *
 * @author jeremiamanogi
 */
public final class Dokter_PoliOld extends javax.swing.JFrame implements ActionListener {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    List<String> jenisLayanan;
    ResultSet hasilDokter;
    protected void datatable(){
        Object[] Baris = {"ID", "Dokter.ID", "Poli.ID", "Spesialis.ID", "Status"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "SELECT * FROM dokter_poli where id like '%" + cariitem + "%' order by id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5)
                });
            }

            tblplgn.setModel(tabmode);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }
    
    protected void aktif(){
        txtid.requestFocus();
    }
    
    protected void kosong(){
        txtid.setText("");
//        txtiddok.setText("");
//        txtidspesial.setText("");
        chkActive.setEnabled(false);
        chkActive.setSelected(true);
                
        try {
            String sql = "SELECT * FROM spesialis";
            Statement stat = conn.createStatement();
            hasilDokter = stat.executeQuery(sql);
            while (hasilDokter.next()){
                String strValue = hasilDokter.getString(2);
                jenisLayanan.add(strValue);
//                hasilSpesialis.getString(2);
            }
        } catch (SQLException e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(
            jenisLayanan.toArray(new String[0])
        ));
//        txtidpoli.setText("");
        txtcari.setText("");
        buttonGroup1.clearSelection();
    }    
    /**
     * Creates new form Pelanggan
     */
    public Dokter_PoliOld() {
        initComponents();
//        if (parent != null || docterParent != null) {
//            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//            addWindowListener(new java.awt.event.WindowAdapter() {
//                @Override
//                public void windowClosing(java.awt.event.WindowEvent e) {
//                    if (parent != null) {
//                        parent.setEnabled(true);
//                        parent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                        parent.datatable();
//                        parent.kosong();
//                        setVisible(false);
//                    }
//
//                    if (docterParent != null) {
//                        docterParent.setEnabled(true);
//                        docterParent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                        docterParent.datatable();
//                        docterParent.kosong();
//                        setVisible(false);
//                    }
//                }
//            });
//        }
        jenisLayanan = new ArrayList<>();

        jenisLayanan.add("Medis");
        jenisLayanan.add("Bedah");
        jenisLayanan.add("Penunjang");
        jenisLayanan.add("Gigi");
        jenisLayanan.add("Kesehatan Jiwa");
        
        aktif();
        kosong();
        datatable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cmbDokter = new javax.swing.JComboBox<>();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpan.setText("Simpan");
        bsimpan.addActionListener();
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel1.setText("Data Spesialis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, -1));

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseMotionListener();
        tblplgn.addMouseListener();
        jScrollPane1.setViewportView(tblplgn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 869, 275));

        txtcari.addKeyListener();
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, -1));

        bcari.setText("Cari");
        bcari.addActionListener();
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        bubah.setText("Ubah");
        bubah.addActionListener();
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        bhapus.setText("Hapus");
        bhapus.addActionListener();
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        bbatal.setText("Batal");
        bbatal.addActionListener();
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        bkeluar.setText("Keluar");
        bkeluar.addActionListener();
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel2.setText("ID Poli");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 240, -1));

        jLabel3.setText("ID Dokter");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel5.setText("ID Spesialis");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        chkActive.setSelected(true);
        chkActive.setText("Status Aktif");
        chkActive.setEnabled(false);
        chkActive.setIconTextGap(8);
        chkActive.addActionListener();
        getContentPane().add(chkActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel7.setText("ID Poli");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 10));

        cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "insert into spesialis (nama, kategori, deskripsi, tahun_pelatihan, aktif) values (?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
//            stat.setString(1, txtiddok.getText());
//            stat.setString(2, cmbCat.getSelectedItem().toString());
//            stat.setString(3, txtidspesial.getText());
//            stat.setInt(4, Integer.parseInt(txtidspesial.getText()));
            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(5, status);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtid.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tblplgnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseMoved

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        try{
            String sql = "update spesialis set nama =?, kategori=?, deskripsi=?, tahun_pelatihan=?, aktif=? where id='"+txtid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);

//            stat.setString(1, txtiddok.getText());
//            stat.setString(2, cmbCat.getSelectedItem().toString());
//            stat.setString(3, txtDesc.getText());
//            stat.setInt(4, Integer.parseInt(txtidspesial.getText()));
            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(5, status);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtid.requestFocus();
            datatable();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from spesialis where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        int bar = tblplgn.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();

        txtid.setText(a);
//        txtiddok.setText(b);
        
        List<String> hasil = new ArrayList<>();
        hasil.add(c);

        for (String item : jenisLayanan) {
            if (!item.contains(c)) {
                hasil.add(item);
            }
        }

//        cmbCat.setModel(new javax.swing.DefaultComboBoxModel<>(
//            hasil.toArray(new String[0])
////           new String[] { "Pilih", "Rawat Jalan", "Rawat Inap" }
//        ));
        
//        txtDesc.setText(d);
//        txtidspesial.setText(e);
        
        chkActive.setEnabled(true);
        chkActive.setSelected(f.equals("1"));
    }//GEN-LAST:event_tblplgnMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void chkActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkActiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JComboBox<String> cmbDokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
