/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dokter;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import koneksi.koneksi;

/**
 *
 * @author Rino Sains
 */
public class Dokter_Poli extends javax.swing.JFrame implements ActionListener {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    List<String> jenisSpesialis;
    List<String> jenisDokter;
    List<String> jenisPoliklinik;

    
    protected void datatable(){
        Object[] Baris = {"ID", "Dokter.ID", "Poli.ID", "Spesialis.ID", "Status"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "SELECT * FROM dokter_poli where id like '%" + cariitem + "%' order by id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5)
                });
            }

            tblplgn.setModel(tabmode);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }
    
    protected void aktif(){
        txtid.requestFocus();
    }
    
    protected void kosong(){
        txtid.setText("");
        chkActive.setEnabled(false);
        chkActive.setSelected(true);
                
        try {
            String sql = "SELECT * FROM spesialis";
            Statement stat = conn.createStatement();
            ResultSet hasilDokter = stat.executeQuery(sql);
            while (hasilDokter.next()){
                String strValue = hasilDokter.getString(2);
                System.out.println("strValue : " + strValue);
                jenisSpesialis.add(strValue);
            }
            cmbSpecialis.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisSpesialis.toArray(new String[0])
            ));
        
        } catch (SQLException e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }

        try {
            String sql = "SELECT * FROM dokter";
            Statement stat = conn.createStatement();
            ResultSet hasilDokter = stat.executeQuery(sql);
            while (hasilDokter.next()){
                String strValue = hasilDokter.getString(2);
                jenisDokter.add(strValue);
            }
            cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisDokter.toArray(new String[0])
            ));
        } catch (SQLException e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        
        try {
            String sql = "SELECT * FROM poliklinik";
            Statement stat = conn.createStatement();
            ResultSet hasilDokter = stat.executeQuery(sql);
            while (hasilDokter.next()){
                String strValue = hasilDokter.getString(2);
                jenisPoliklinik.add(strValue);
            }
            cmbPoli.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisPoliklinik.toArray(new String[0])
            ));
        } catch (SQLException e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        
//                dokter
        
//        txtidpoli.setText("");
        txtcari.setText("");
        buttonGroup1.clearSelection();
    }    
    /**
     * Creates new form Pelanggan
     */
    public Dokter_Poli() {
        initComponents();
        jenisSpesialis = new ArrayList<>();
        jenisDokter = new ArrayList<>();
        jenisPoliklinik = new ArrayList<>();
        aktif();
        kosong();
        datatable();
       
    }

    /**
     * Creates new form Dokter_Poli2
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cmbPoli = new javax.swing.JComboBox<>();
        cmbSpecialis = new javax.swing.JComboBox<>();
        cmbDokter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Spesialis");

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblplgnMouseMoved(evt);
            }
        });
        tblplgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblplgn);

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Poli");

        txtid.setEnabled(false);

        jLabel3.setText("ID Dokter");

        jLabel5.setText("ID Spesialis");

        chkActive.setSelected(true);
        chkActive.setText("Status Aktif");
        chkActive.setEnabled(false);
        chkActive.setIconTextGap(8);
        chkActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActiveActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Poli");

        cmbPoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSpecialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(chkActive))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bsimpan)
                        .addGap(5, 5, 5)
                        .addComponent(bubah)
                        .addGap(19, 19, 19)
                        .addComponent(bhapus)
                        .addGap(13, 13, 13)
                        .addComponent(bbatal)
                        .addGap(19, 19, 19)
                        .addComponent(bkeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bcari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbSpecialis, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbPoli, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSpecialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(chkActive)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsimpan)
                    .addComponent(bubah)
                    .addComponent(bhapus)
                    .addComponent(bbatal)
                    .addComponent(bkeluar))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "insert into dokter_poli (dokter_id, poli_id, spesialis_id, status) values (?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            String getSelectedDocter = cmbDokter.getSelectedItem().toString();
            String getSelectedPoli = cmbPoli.getSelectedItem().toString();
            String getSelectedSpes = cmbSpecialis.getSelectedItem().toString();
            int getDokterId;
            int getPoliId;
            int getSpecialisId;
            try {
                String sql2 = "SELECT * FROM dokter";
                Statement stat2 = conn.createStatement();
                ResultSet resSet = stat2.executeQuery(sql2);
                while (resSet.next()){
                    String strValue = resSet.getString(2);
                    if (getSelectedDocter.equals(strValue)) {
                        getDokterId = resSet.getInt(1);
                        stat.setInt(1, getDokterId);
                        break;
                    }
                }  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
            }
            
            try {
                String sql2 = "SELECT * FROM poliklinik";
                Statement stat2 = conn.createStatement();
                ResultSet resSet = stat2.executeQuery(sql2);
                while (resSet.next()){
                    String strValue = resSet.getString(2);
                    if (getSelectedPoli.equals(strValue)) {
                        getPoliId = resSet.getInt(1);
                        stat.setInt(2, getPoliId);
                        break;
                    }
                }  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
            }
                       
            try {
                String sql2 = "SELECT * FROM spesialis";
                Statement stat2 = conn.createStatement();
                ResultSet resSet = stat2.executeQuery(sql2);
                while (resSet.next()){
                    String strValue = resSet.getString(2);
                    if (getSelectedSpes.equals(strValue)) {
                        getSpecialisId = resSet.getInt(1);
                        stat.setInt(3, getSpecialisId);
                        break;
                    }
                }  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
            }
            
            stat.setInt(4, chkActive.isSelected() ? 1 : 0);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtid.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tblplgnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseMoved

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        int bar = tblplgn.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();

        txtid.setText(a);
        List<String> hasil = new ArrayList<>();
        hasil.add(a);

        try {
            jenisDokter.clear();
            String sql = "SELECT * FROM dokter";
            Statement stat = conn.createStatement();
            ResultSet hasilDokter = stat.executeQuery(sql);
            jenisDokter.add(b);
            while (hasilDokter.next()){
                String strValue = hasilDokter.getString(2);
                if (!strValue.contains(b)) {
                    jenisDokter.add(strValue);
                }
            }
            cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisDokter.toArray(new String[0])
            ));
        } catch (SQLException e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }

        try {
            jenisPoliklinik.clear();
            String sql = "SELECT * FROM poliklinik";
            Statement stat = conn.createStatement();
            ResultSet hasilDokter = stat.executeQuery(sql);
            jenisPoliklinik.add(c);
            while (hasilDokter.next()){
                String strValue = hasilDokter.getString(2);
                if (!strValue.contains(b)) {
                    jenisPoliklinik.add(strValue);
                }
            }
            cmbPoli.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisPoliklinik.toArray(new String[0])
            ));
        } catch (SQLException e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        
        try {
            jenisSpesialis.clear();
            String sql = "SELECT * FROM spesialis";
            Statement stat = conn.createStatement();
            ResultSet hasilDokter = stat.executeQuery(sql);
            jenisSpesialis.add(d);
            while (hasilDokter.next()){
                String strValue = hasilDokter.getString(2);
                jenisSpesialis.add(strValue);
            }
            cmbSpecialis.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisSpesialis.toArray(new String[0])
            ));
        } catch (SQLException e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    chkActive.setEnabled(true);
//    chkActive.setSelected(f.equals("1"));
    }//GEN-LAST:event_tblplgnMouseClicked

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        try{
            String sql = "update spesialis set nama =?, kategori=?, deskripsi=?, tahun_pelatihan=?, aktif=? where id='"+txtid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);

            //            stat.setString(1, txtiddok.getText());
            //            stat.setString(2, cmbCat.getSelectedItem().toString());
            //            stat.setString(3, txtDesc.getText());
            //            stat.setInt(4, Integer.parseInt(txtidspesial.getText()));
            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(5, status);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtid.requestFocus();
            datatable();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from spesialis where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void chkActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkActiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter_Poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter_Poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter_Poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter_Poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter_Poli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JComboBox<String> cmbDokter;
    private javax.swing.JComboBox<String> cmbPoli;
    private javax.swing.JComboBox<String> cmbSpecialis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
