/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dokter;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author jeremiamanogi
 */
public class Dokter extends javax.swing.JFrame implements ActionListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dokter.class.getName());
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    List<String> jenisLayanan;
    ResultSet hasilSpesialis;
    protected void datatable(){
        Object[] Baris = {"ID", "Nama Dokter", "Email", "No.Telepon", "Spesialis Utama", "Tahun Lulus", "Aktif"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
          String sql = "SELECT r.id, r.nama, r.email, r.phone, p.nama, r.tahun_lulus, r.active FROM dokter r INNER JOIN spesialis p ON r.id_spesialis_utama= p.id"+
                  " where r.nama like '%" + cariitem + "%' or p.nama like '%" + cariitem + "%' order by id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),
                });
            }

            tblplgn.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        
        try {
            String sql = "SELECT * FROM spesialis";
            Statement stat = conn.createStatement();
            hasilSpesialis = stat.executeQuery(sql);
            while (hasilSpesialis.next()){
                String strValue = hasilSpesialis.getString(2);
                jenisLayanan.add(strValue);
//                hasilSpesialis.getString(2);
            }
        } catch (Exception e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }
    
    protected void kosong(){
        txtid.setText("");
        txtnm.setText("");
        txtemail.setText("");
        txtphone.setText("");
        txtThnLulus.setText("");

        try {
            jenisLayanan.clear();
            String sql = "SELECT * FROM spesialis";
            Statement stat = conn.createStatement();
            hasilSpesialis = stat.executeQuery(sql);
            while (hasilSpesialis.next()){
                String strValue = hasilSpesialis.getString(2);
                jenisLayanan.add(strValue);
            }
            cmbSpes.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisLayanan.toArray(new String[0])
            ));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        txtcari.setText("");
        chkActive.setSelected(true);
        chkActive.setEnabled(false);
    }    
    
    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
        jenisLayanan = new ArrayList<>();
        aktif();
        datatable();
        kosong();
       
    }
    
    protected void aktif(){
        txtnm.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtThnLulus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        btnBukaPoliklinik = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbSpes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data Dokter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 246, -1));

        jLabel2.setText("ID Dokter");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setText("Nama Dokter");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 246, -1));

        jLabel4.setText("Email Dokter");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 246, -1));

        jLabel5.setText("Nomor Telefon Dokter");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 246, -1));

        jLabel6.setText("Spesialis Utama");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(txtThnLulus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 246, -1));

        jLabel7.setText("Tahun Lulus");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        chkActive.setSelected(true);
        chkActive.setText("Status Aktif");
        chkActive.setEnabled(false);
        chkActive.setIconTextGap(8);
        chkActive.addActionListener();
        getContentPane().add(chkActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        bsimpan.setText("Simpan");
        bsimpan.addActionListener();
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 293, -1, -1));

        bubah.setText("Ubah");
        bubah.addActionListener();
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 293, -1, -1));

        bhapus.setText("Hapus");
        bhapus.addActionListener();
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 293, -1, -1));

        bbatal.setText("Batal");
        bbatal.addActionListener();
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 293, -1, -1));

        bkeluar.setText("Keluar");
        bkeluar.addActionListener();
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 293, -1, -1));

        txtcari.addKeyListener();
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 322, 140, -1));

        bcari.setText("Cari");
        bcari.addActionListener();
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 322, -1, -1));

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseMotionListener();
        tblplgn.addMouseListener();
        jScrollPane1.setViewportView(tblplgn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 351, 869, 275));

        btnBukaPoliklinik.setText("Lihat Form Spesialis");
        btnBukaPoliklinik.addActionListener();
        getContentPane().add(btnBukaPoliklinik, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel8.setText("<html>Jika Spesialis Tidak dalam Pilihan<br>Tambahkan di Form Spesialis</html>");
        jLabel8.setAlignmentY(1.0F);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 210, 40));

        getContentPane().add(cmbSpes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkActiveActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "insert into dokter (nama, email, phone, id_spesialis_utama, tahun_lulus, active) values (?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnm.getText());
            stat.setString(2, txtemail.getText());
            stat.setString(3, txtphone.getText());
            String getSelectedValue = cmbSpes.getSelectedItem().toString();
            int getId;
            try {
                String sql2 = "SELECT * FROM spesialis";
                Statement stat2 = conn.createStatement();
                hasilSpesialis = stat2.executeQuery(sql2);
                while (hasilSpesialis.next()){
                    String strValue = hasilSpesialis.getString(2);
                    if (getSelectedValue.equals(strValue)) {
                        getId = hasilSpesialis.getInt(1);
                        stat.setInt(4, getId);
                        break;
                    }
                }  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
            }

            stat.setInt(5, Integer.parseInt(txtThnLulus.getText()));
            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(6, status);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtid.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        try{
            String sql = "update dokter set nama =?, email=?, phone=?, id_spesialis_utama=?, tahun_lulus=?, active=? where id='"+txtid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, txtnm.getText());
            stat.setString(2, txtemail.getText());
            stat.setString(3, txtphone.getText());
            String getSelectedValue = cmbSpes.getSelectedItem().toString();
            int getId;
            try {
                String sql2 = "SELECT * FROM spesialis";
                Statement stat2 = conn.createStatement();
                hasilSpesialis = stat2.executeQuery(sql2);
                while (hasilSpesialis.next()){
                    String strValue = hasilSpesialis.getString(2);
                    if (getSelectedValue.equals(strValue)) {
                        getId = hasilSpesialis.getInt(1);
                        stat.setInt(4, getId);
                        break;
                    }
                }  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
            }

 
            stat.setInt(5, Integer.parseInt(txtThnLulus.getText()));
            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(6, status);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtid.requestFocus();
            datatable();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from spesialis where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void tblplgnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseMoved

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        int bar = tblplgn.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();

        txtid.setText(a);
        txtnm.setText(b);
        txtemail.setText(c);
        txtphone.setText(d);

        
        List<String> hasil = new ArrayList<>();
        hasil.add(e);

        for (String item : jenisLayanan) {
            if (!item.contains(c)) {
                hasil.add(item);
            }
        }

        cmbSpes.setModel(new javax.swing.DefaultComboBoxModel<>(
            hasil.toArray(new String[0])
        ));

        txtThnLulus.setText(f);

        chkActive.setEnabled(true);
        chkActive.setSelected(g.equals("1"));
    }//GEN-LAST:event_tblplgnMouseClicked

    private void btnBukaPoliklinikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaPoliklinikActionPerformed
        this.setEnabled(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Spesialis spesies = new Spesialis(null, this);
        spesies.setLocationRelativeTo(null);
        spesies.setSize(925, 700); // sesuaikan ukuran
        spesies.setVisible(true);
    }//GEN-LAST:event_btnBukaPoliklinikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dokter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btnBukaPoliklinik;
    private javax.swing.JButton bubah;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JComboBox<String> cmbSpes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextField txtThnLulus;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
