/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dokter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import koneksi.koneksi;
/**
 *
 * @author jeremiamanogi
 */
public class Poliklinik extends javax.swing.JFrame implements ActionListener {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    List<String> jenisLayanan;
    ResultSet hasilSpesialis;
    protected void datatable(){
        Object[] Baris = {"ID", "Nama Poliklinik", "Nama Spesialis", "Nama kategori", "Deskripsi Kategori"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
          String sql = "SELECT r.id, r.nama, p.nama, p.kategori, p.deskripsi FROM poliklinik r INNER JOIN spesialis p ON r.id_spesialis_utama= p.id"+
                  " where r.nama like '%" + cariitem + "%' or p.nama like '%" + cariitem + "%' or p.kategori like '%" + cariitem + "%' order by id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                });
            }

            tblplgn.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        
        try {
            String sql = "SELECT * FROM spesialis";
            Statement stat = conn.createStatement();
            hasilSpesialis = stat.executeQuery(sql);
            while (hasilSpesialis.next()){
                String strValue = hasilSpesialis.getString(2);
                jenisLayanan.add(strValue);
//                hasilSpesialis.getString(2);
            }
        } catch (Exception e) {
            System.out.print("strValue : " + e);
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }
    
    protected void aktif(){
        txtid.requestFocus();
    }
    
    protected void kosong(){
        txtid.setText("");
        txtnm.setText("");
//        txtDesc.setText("");
//        chkActive.setEnabled(false);
//        chkActive.setSelected(true);
//        cmbSpes.setModel(new javax.swing.DefaultComboBoxModel<>(
//            jenisLayanan.toArray(new String[0])
//        ));
//        txtThnPelatihan.setText("");
        try {
            jenisLayanan.clear();
            String sql = "SELECT * FROM spesialis";
            Statement stat = conn.createStatement();
            hasilSpesialis = stat.executeQuery(sql);
            while (hasilSpesialis.next()){
                String strValue = hasilSpesialis.getString(2);
                jenisLayanan.add(strValue);
            }
            cmbSpes.setModel(new javax.swing.DefaultComboBoxModel<>(
                jenisLayanan.toArray(new String[0])
            ));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
        txtcari.setText("");
        buttonGroup1.clearSelection();
    }    
    /**
     * Creates new form Pelanggan
     */
    public Poliklinik() {
        initComponents();
        jenisLayanan = new ArrayList<>();
        aktif();
        datatable();
        kosong();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbSpes = new javax.swing.JComboBox<>();
        btnBukaPoliklinik = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpan.setText("Simpan");
        // bsimpan.addActionListener();
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel1.setText("Data Poliklinik");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, -1));

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        // tblplgn.addMouseMotionListener();
        // tblplgn.addMouseListener();
        tblplgn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblplgnMouseMoved(evt);
            }
        });
        tblplgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(tblplgn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 869, 275));

        // txtcari.addKeyListener();
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, -1));

        bcari.setText("Cari");
        // bcari.addActionListener();
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        bubah.setText("Ubah");
        // bubah.addActionListener();
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        bhapus.setText("Hapus");
        // bhapus.addActionListener();
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        bbatal.setText("Batal");
        // bbatal.addActionListener();
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        bkeluar.setText("Keluar");
        // bkeluar.addActionListener();
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel2.setText("ID Poliklinik");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 32, -1, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 29, 246, -1));

        jLabel3.setText("Nama Poliklinik");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 58, -1, -1));
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 58, 246, -1));

        jLabel4.setText("Nama Spesialis");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 87, -1, -1));

        getContentPane().add(cmbSpes, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 87, 246, -1));

        btnBukaPoliklinik.setText("Lihat Tabel Spesialis");
        // btnBukaPoliklinik.addActionListener();
        btnBukaPoliklinik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukaPoliklinikActionPerformed(evt);
            }
        });
        getContentPane().add(btnBukaPoliklinik, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "insert into poliklinik (nama, id_spesialis_utama) values (?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnm.getText());
            String getSelectedValue = cmbSpes.getSelectedItem().toString();
            int getId;
            try {
                String sql2 = "SELECT * FROM spesialis";
                Statement stat2 = conn.createStatement();
                hasilSpesialis = stat2.executeQuery(sql2);
                while (hasilSpesialis.next()){
                    String strValue = hasilSpesialis.getString(2);
                    if (getSelectedValue.equals(strValue)) {
                        getId = hasilSpesialis.getInt(1);
                        stat.setInt(2, getId);
                        break;
                    }
                }  
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
            }


            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtid.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tblplgnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseMoved

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        try{
            String sql = "update poliklinik set nama =?, id_spesialis_utama=? where id='"+txtid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, txtnm.getText());
            String getSelectedValue = cmbSpes.getSelectedItem().toString();
            int getId;
            try {
//                String sql2 = "SELECT * FROM spesialis";
//                Statement stat2 = conn.createStatement();
//                hasilSpesialis = stat.executeQuery(sql);

                String sql2 = "SELECT * FROM spesialis";
                Statement stat2 = conn.createStatement();
                hasilSpesialis = stat2.executeQuery(sql2);
                
                while (hasilSpesialis.next()){
                    String strValue = hasilSpesialis.getString(2);
                    if (getSelectedValue.equals(strValue)) {
                        getId = hasilSpesialis.getInt(1);
                        stat.setInt(2, getId);
                        break;
                    }
                }  
            } catch (Exception e) {
                System.out.print("stat : " + e.toString());
                JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
            }
            System.out.print("stat : " + stat.toString());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtid.requestFocus();
            datatable();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from poliklinik where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        int bar = tblplgn.getSelectedRow();
//        Object[] Baris = {"ID", "Nama Poliklinik", "Nama Spesialis", "Nama kategori", "Deskripsi Kategori"};
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();


        txtid.setText(a);
        txtnm.setText(b);
        
        List<String> hasil = new ArrayList<>();
        hasil.add(c);

        for (String item : jenisLayanan) {
            if (!item.contains(c)) {
                hasil.add(item);
            }
        }

        cmbSpes.setModel(new javax.swing.DefaultComboBoxModel<>(
            hasil.toArray(new String[0])
        ));
        
//        txtDesc.setText(d);
//        txtThnPelatihan.setText(e);
//        
//        chkActive.setEnabled(true);
//        chkActive.setSelected(f.equals("1"));
    }//GEN-LAST:event_tblplgnMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void btnBukaPoliklinikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaPoliklinikActionPerformed
        this.setEnabled(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Spesialis spesies = new Spesialis(this, null);
        spesies.setLocationRelativeTo(null); 
        spesies.setSize(925, 700); // sesuaikan ukuran
        spesies.setVisible(true);
    }//GEN-LAST:event_btnBukaPoliklinikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btnBukaPoliklinik;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbSpes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
