/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dokter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import koneksi.koneksi;
/**
 *
 * @author jeremiamanogi
 */
public class SpesialisOld extends javax.swing.JFrame implements ActionListener {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    List<String> jenisLayanan;
    protected void datatable(){
        Object[] Baris = {"ID", "Nama", "Kategori", "Deskripsi", "Thn.Pelatihan", "Aktif"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "SELECT * FROM spesialis where kategori like '%" + cariitem + "%' or nama like '%" + cariitem + "%' order by id asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6)
                });
            }

            tblplgn.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }
    
    protected void aktif(){
        txtid.requestFocus();
    }
    
    protected void kosong(){
        txtid.setText("");
        txtnm.setText("");
        txtDesc.setText("");
        chkActive.setEnabled(false);
        chkActive.setSelected(true);
        cmbCat.setModel(new javax.swing.DefaultComboBoxModel<>(
            jenisLayanan.toArray(new String[0])
        ));
        txtThnPelatihan.setText("");
        txtcari.setText("");
        buttonGroup1.clearSelection();
    }    
    /**
     * Creates new form Pelanggan
     */
    public SpesialisOld(PoliklinikOld parent, DokterOld docterParent) {
        initComponents();
        if (parent != null || docterParent != null) {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    if (parent != null) {
                        parent.setEnabled(true);
                        parent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        parent.datatable();
                        parent.kosong();
                        setVisible(false);
                    }

                    if (docterParent != null) {
                        docterParent.setEnabled(true);
                        docterParent.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        docterParent.datatable();
                        docterParent.kosong();
                        setVisible(false);
                    }
                }
            });
        }
        jenisLayanan = new ArrayList<>();

        jenisLayanan.add("Medis");
        jenisLayanan.add("Bedah");
        jenisLayanan.add("Penunjang");
        jenisLayanan.add("Gigi");
        jenisLayanan.add("Kesehatan Jiwa");
        
        aktif();
        kosong();
        datatable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkActive = new javax.swing.JCheckBox();
        cmbCat = new javax.swing.JComboBox<>();
        txtThnPelatihan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpan.setText("Simpan");
        bsimpan.addActionListener();
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 293, -1, -1));

        jLabel1.setText("Data Spesialis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, -1));

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseMotionListener();
        tblplgn.addMouseListener();
        jScrollPane1.setViewportView(tblplgn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 351, 869, 275));

        txtcari.addKeyListener();
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 322, 140, -1));

        bcari.setText("Cari");
        bcari.addActionListener();
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 322, -1, -1));

        bubah.setText("Ubah");
        bubah.addActionListener();
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 293, -1, -1));

        bhapus.setText("Hapus");
        bhapus.addActionListener();
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 293, -1, -1));

        bbatal.setText("Batal");
        bbatal.addActionListener();
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 293, -1, -1));

        bkeluar.setText("Keluar");
        bkeluar.addActionListener();
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 293, -1, -1));

        jLabel2.setText("ID Spesialis");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 32, -1, -1));

        txtid.setEnabled(false);
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 29, 246, -1));

        jLabel3.setText("Nama Spesialis");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 58, -1, -1));
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 58, 246, -1));

        jLabel4.setText("Kategori");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 87, -1, -1));

        jLabel5.setText("Deskripsi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 121, -1, -1));

        jLabel6.setText("Tahun pelatihan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 222, -1, -1));

        chkActive.setSelected(true);
        chkActive.setText("Status Aktif");
        chkActive.setEnabled(false);
        chkActive.setIconTextGap(8);
        chkActive.addActionListener();
        getContentPane().add(chkActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 254, -1, -1));

        cmbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medis", "Bedah", "Penunjang", "Gigi", "Kesehatan Jiwa" }));
        getContentPane().add(cmbCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 87, 246, -1));

        txtThnPelatihan.addActionListener();
        getContentPane().add(txtThnPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 219, 246, -1));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane2.setViewportView(txtDesc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 121, 246, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String sql = "insert into spesialis (nama, kategori, deskripsi, tahun_pelatihan, aktif) values (?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnm.getText());
            stat.setString(2, cmbCat.getSelectedItem().toString());
            stat.setString(3, txtDesc.getText());
            stat.setInt(4, Integer.parseInt(txtThnPelatihan.getText()));
            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(5, status);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtid.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tblplgnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblplgnMouseMoved

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        try{
            String sql = "update spesialis set nama =?, kategori=?, deskripsi=?, tahun_pelatihan=?, aktif=? where id='"+txtid.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, txtnm.getText());
            stat.setString(2, cmbCat.getSelectedItem().toString());
            stat.setString(3, txtDesc.getText());
            stat.setInt(4, Integer.parseInt(txtThnPelatihan.getText()));
            int status = chkActive.isSelected() ? 1 : 0;
            stat.setInt(5, status);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtid.requestFocus();
            datatable();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from spesialis where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtid.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        int bar = tblplgn.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();

        txtid.setText(a);
        txtnm.setText(b);
        
        List<String> hasil = new ArrayList<>();
        hasil.add(c);

        for (String item : jenisLayanan) {
            if (!item.contains(c)) {
                hasil.add(item);
            }
        }

        cmbCat.setModel(new javax.swing.DefaultComboBoxModel<>(
            hasil.toArray(new String[0])
//           new String[] { "Pilih", "Rawat Jalan", "Rawat Inap" }
        ));
        
        txtDesc.setText(d);
        txtThnPelatihan.setText(e);
        
        chkActive.setEnabled(true);
        chkActive.setSelected(f.equals("1"));
    }//GEN-LAST:event_tblplgnMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void chkActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkActiveActionPerformed

    private void txtThnPelatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThnPelatihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThnPelatihanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JComboBox<String> cmbCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtThnPelatihan;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
